# Generated by Django 4.0.3 on 2022-04-18 23:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('specs', models.TextField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fecha_pub', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Trabajo/Serv', 'Trabajo/Serv'), ('Pregunta', 'Pregunta'), ('General', 'General')], default='General', max_length=13)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img_perfil', models.ImageField(blank=True, null=True, upload_to='img/perfil')),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('precio', models.IntegerField()),
                ('specs', models.TextField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fecha_pub', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
