# Generated by Django 4.0.3 on 2022-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='specs',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
