# Generated by Django 4.0.3 on 2022-03-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0002_articulo_precio_articulo_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.CreateModel(
            name='ArticuloImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('arti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferre.articulo')),
            ],
        ),
    ]
