# Generated by Django 4.0.3 on 2022-04-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0003_perfil_img_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='img_perfil',
        ),
    ]
