# Generated by Django 4.0.3 on 2022-03-29 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0003_articulo_img_articuloimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_pub',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.DeleteModel(
            name='ArticuloImage',
        ),
    ]
