# Generated by Django 4.0.3 on 2022-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0004_remove_perfil_img_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img/perfil'),
        ),
    ]
