# Generated by Django 4.0.3 on 2022-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0007_perfil_sitio_web'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img/perfil'),
        ),
    ]
