# Generated by Django 4.0.3 on 2022-04-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_alter_comentario_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
