# Generated by Django 4.0.3 on 2022-04-18 23:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miembros', '0003_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pub', models.TimeField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ferre.articulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_pub'],
            },
        ),
    ]
